routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('upload/temp', 'Controller@uploadTemp')->name('upload.temp');

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group([ 'prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ] ], function (){
    Route::group(['prefix' => 'backend', 'namespace' => 'backend'], function($route) {
        Route::group(['namespace' => 'Auth'], function () {
            //Admin Login
            Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
            Route::post('login', 'LoginController@login')->name('admin.login');
            Route::get('logout', 'LoginController@logout')->name('admin.logout');
            //Admin Passwords
            Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.send.reset');
            Route::post('password/reset', 'ResetPasswordController@reset')->name('admin.reset');
            Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.reset');
            Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.reset.form');
        });

        Route::group(['middleware' => 'admin'], function () {
            Route::resource('navigations', 'NavigationsController')->except('show');
            Route::resource('slides', 'SlidesController')->except('show');
            Route::resource('countries', 'CountriesController')->except('show');
            Route::resource('cities', 'CitiesController')->except('show');
            Route::get('cities/country/{coid}/{ctid?}', 'CitiesController@country')->name('cities.country');
            Route::resource('pages', 'PagesController')->except('show');
            Route::resource('admins', 'AdminsController')->except('show');
            Route::resource('users', 'UsersController')->except('show');
            Route::get('users/generate', 'UsersController@generate')->name('users.generate');
            Route::resource('visa', 'VisasController')->except('show');
            Route::get('visa/requests', 'VisasController@requests')->name('visa.requests');
            Route::get('visa/request/{id}', 'VisasController@showRequest')->name('visa.request');
            Route::post('visa/request/edit', 'VisasController@updateRequest')->name('visa.request.edit');
            Route::get('documents/{visa}', 'DocumentsController@index')->name('documents.index');
            Route::get('documents/create/{visa}', 'DocumentsController@create')->name('documents.create');
            Route::resource('documents', 'DocumentsController')->except('index','create','show');

            Route::resource('hotels', 'HotelsController')->except('show');
            Route::match(['get','post'], 'hotels/album/{hotel}', 'HotelsController@album')->name('hotels.album');
            Route::get('hotels/album/makeFeatured/{photo}', 'HotelsController@makeFeatured')->name('hotels.album.featured');
            Route::delete('hotels/photo/{photo}', 'HotelsController@destroyPhoto')->name('hotels.photo.destroy');
            Route::get('hotels/requests', 'HotelsController@requests')->name('hotels.requests');
            Route::get('hotels/request/{id}', 'HotelsController@showRequest')->name('hotels.request');
            Route::post('hotels/request/edit', 'HotelsController@updateRequest')->name('hotels.request.edit');
            Route::get('hotels/custom/requests', 'HotelsController@requestsCustom')->name('hotels.requests-custom');
            Route::get('hotels/request/custom/{id}', 'HotelsController@showRequestCustom')->name('hotels.request.custom');
            Route::post('hotels/request/custom/edit', 'HotelsController@updateRequestCustom')->name('hotels.request.custom.edit');

            Route::resource('amenities', 'AmenitiesController')->except('show', 'create', 'edit', 'update');

            Route::post('rooms/removePhoto', 'RoomsController@removeImg')->name('room.photo.delete');
            Route::get('rooms/{hotel}', 'RoomsController@index')->name('rooms.index');
            Route::get('rooms/create/{hotel}', 'RoomsController@create')->name('rooms.create');
            Route::resource('rooms', 'RoomsController')->except('show', 'index', 'create');

            Route::resource('trips', 'TripsController')->except('show');
            Route::get('trips/requests', 'TripsController@requests')->name('trips.requests');
            Route::get('trips/request/{id}', 'TripsController@showRequest')->name('trips.request');
            Route::match(['get','post'], 'trips/album/{trip}', 'TripsController@album')->name('trips.album');
            Route::post('trips/request/edit', 'TripsController@updateRequest')->name('trips.request.edit');
            Route::get('trips/album/makeFeatured/{photo}', 'TripsController@makeFeatured')->name('trips.album.featured');
            Route::delete('trips/photo/{photo}', 'TripsController@destroyPhoto')->name('trips.photo.destroy');

            Route::get('flights/requests', 'FlightsController@requests')->name('flights.requests');
            Route::get('flights/request/{id}', 'FlightsController@showRequest')->name('flights.request');
            Route::post('flights/request/edit', 'FlightsController@updateRequest')->name('flights.request.edit');

            Route::match(['get', 'post'], 'settings', 'SettingsController@index')->name('settings');            // Site Settings
            Route::match(['get', 'post'], 'terms', 'SettingsController@terms')->name('terms');                  // Terms Settings
            Route::match(['get', 'post'], 'contacts', 'SettingsController@contacts')->name('contacts');         // Contacts Info Settings
            Route::get('contact-us', 'DashboardController@contact')->name('contact-us');                                    // Contact Us Emails
            Route::get('newsletter', 'NewsletterController@index')->name('newsletter');                                    // Backend Dashboard
            Route::post('newsletter', 'NewsletterController@send')->name('newsletter');                                    // Backend Dashboard
            Route::get('/', 'DashboardController@index')->name('dashboard');                                    // Backend Dashboard
        });
    });

    Route::group(['namespace' => 'frontend'], function($route) {
        Route::group(['middleware' => 'user'], function (){
            Route::get('profile', 'UsersController@profile')->name('site.profile');
            Route::put('profile', 'UsersController@profileHandle')->name('site.profile');

            Route::get('agency/trips', 'UsersController@trips')->name('agency.trips');
            Route::match(['get', 'post'], 'agency/trips/create', 'UsersController@createTrip')->name('agency.trips.create');
            Route::match(['get', 'put'], 'agency/trips/edit/{id}', 'UsersController@editTrip')->name('agency.trips.edit');
            Route::delete('agency/trips/destroy/{id}', 'UsersController@destroyTrip')->name('agency.trips.destroy');
            Route::match(['get', 'post'], 'agency/trips/album/{trip}', 'UsersController@tripAlbum')->name('agency.trips.album');
            Route::get('agency/trips/album/makeFeatured/{photo}', 'UsersController@makeFeatured')->name('agency.trips.album.featured');
            Route::delete('agency/trips/photo/{photo}', 'UsersController@destroyPhoto')->name('agency.trips.photo.destroy');

            Route::post('visa-request', 'VisasController@visaRequest')->name('site.visa.request');
            Route::get('my-visas', 'VisasController@myVisasRequests')->name('site.my-visas');

            Route::post('hotels/special', 'HotelsController@custom')->name('site.hotels.custom');
            Route::post('hotels/bookingConfirm', 'HotelsController@bookingConfirm')->name('site.hotels.booking.confirm');
            Route::post('hotels/{id}', 'HotelsController@booking')->name('site.hotels.booking');
            Route::get('my-hotels', 'HotelsController@myHotelsRequests')->name('site.my-hotels');
            Route::get('my-hotels/special', 'HotelsController@myHotelsRequestsCustom')->name('site.my-hotels.custom');

            Route::post('trips/{id}', 'TripsController@bookingConfirm')->name('site.trips.booking');
            Route::get('my-trips', 'TripsController@myTripsRequests')->name('site.my-trips');
            Route::get('my-trips-requests', 'TripsController@agencyTripsRequests')->name('site.agency-trips-requests');

            Route::post('flights/booking', 'FlightsController@booking')->name('site.flight.booking');
            Route::get('my-flights', 'FlightsController@myFlightsRequests')->name('site.my-flights');
            Route::get('flight/{id}', 'FlightsController@show')->name('site.flight.show');

            Route::get('payments/upload/{action}/{id}', 'PaymentsController@paymentUpload')->name('site.payments.upload');
            Route::post('payments/upload', 'PaymentsController@paymentUploadHandle')->name('site.payments.upload.post');
        });

        Auth::routes();
        Route::get('register/agency', 'Auth\RegisterController@showAgencyRegistrationForm')->name('register.agency');

app/Models/Visa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Visa extends Model
{
    protected $guarded = ['id'];

    public static $rules = [
        'title_ar' => 'required', 'title_fr' => 'required', 'price' => 'required'
    ];

    public function getTitleAttribute()
    {
        return $this->{"title_".\LaraLocale::getCurrentLocale()};
    }

    public function getDescriptionAttribute()
    {
        return $this->{"description_".\LaraLocale::getCurrentLocale()};
    }

    public function country()
    {
        return $this->belongsTo('App\Models\Country', 'country_id');
    }

    public function documents()
    {
        return $this->hasMany('App\Models\Document');
    }
}

app/Http/Controllers/backend/AdminsController.php
<?php

namespace App\Http\Controllers\backend;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class AdminsController extends Controller
{
    protected $viewPath = 'backend.admins.';
    protected $data  = [];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['allUsers'] = Admin::all();
        return view($this->viewPath.'list', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = trans('users.create-admin');
        return view($this->viewPath.'form', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, Admin::rules());

        $admin = new Admin();
        if($admin->insert($this->getInputs($request)))
            return redirect(route('admins.index'))->with('msg', trans('common.add-success'));

        return redirect(route('admins.index'))->with('msg', trans('common.add-failed'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['title'] = trans('users.update-admin');
        $this->data['userData'] = Admin::find($id);
        return view($this->viewPath.'form', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [ 'name' => 'required' ];
        if(!empty($request->password))
            $rules['password'] = 'required|min:3';
        $this->validate($request, Admin::rules());

        $admin = Admin::find($id);
        if($admin->update($this->getInputs($request)))
            return redirect(route('admins.index'))->with('msg', trans('common.update-success'));

        return redirect(route('admins.index'))->with('msg', trans('common.update-failed'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Admin::destroy($id)){
            return back()->with('msg', trans('common.delete-success'));
        }else{
            return back()->with('msg', trans('common.delete-failed'));
        }
    }

    protected function getInputs($request)
    {
        $inputs = $request->only(['name', 'email', 'phone']);

        if($request->isMethod('put')) {
            $inputs['password'] = Hash::make($request->password);
            $inputs['updated_by'] = \Auth::guard('admin')->user()->id;
        }else {
            if(!empty($request->password))
                $inputs['password'] = Hash::make($request->password);

            $inputs['created_by'] = \Auth::guard('admin')->user()->id;
        }

        return $inputs;
    }
}

app/Http/Controllers/backend/AmenitiesController.php
<?php

namespace App\Http\Controllers\backend;

use App\Models\Amenity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AmenitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allAmenities = Amenity::all();
        return view('backend.hotels.amenities', compact('allAmenities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['title_ar' => 'required', 'title_fr' => 'required']);

        $country = new Amenity();
        if($country->insert($request->only(['title_ar', 'title_fr', 'icon'])))
            return redirect(route('amenities.index'))->with('msg', trans('common.add-success'));

        return redirect(route('amenities.index'))->with('msg', trans('common.add-failed'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Amenity::destroy($id))
            return back()->with('msg', trans('common.delete-success'));

        return back()->with('msg', trans('common.delete-failed'));
    }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Models\Contact;
use App\Models\Flight;
use App\Models\HotelCustom;
use App\Models\UserHotel;
use App\Models\UserTrip;
use App\Models\UserVisa;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $latestVisaRequests = UserVisa::whereStatus('pending')->orWhere('status', 'progress')->orderBy('id')->take(5)->get();
        $latestHotelsRequests = UserHotel::whereStatus('pending')->orWhere('status', 'progress')->orderBy('id')->take(5)->get();
        $latestTripsRequests = UserTrip::whereStatus('pending')->orWhere('status', 'progress')->orderBy('id')->take(5)->get();
        $latestFlightsRequests = Flight::whereStatus('pending')->orderBy('id')->take(5)->get();
        $latestHotelsCustomRequests = HotelCustom::whereStatus('pending')->orderBy('id')->take(5)->get();
        return view('backend.dashboard', compact('latestVisaRequests', 'latestHotelsRequests', 'latestTripsRequests', 'latestFlightsRequests', 'latestHotelsCustomRequests'));
    }

    public function contact()
    {
        $emails = Contact::all();
        return view('backend.contact-us', compact('emails'));
    }
}

app/Http/Controllers/backend/FlightsController.php
<?php

namespace App\Http\Controllers\backend;

use App\Models\Flight;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FlightsController extends Controller
{
    protected $viewPath = 'backend.flights.';

    public function requests()
    {
        $allRequests = Flight::all();
        return view($this->viewPath.'requests', compact('allRequests'));
    }

    public function showRequest($id)
    {
        $request = Flight::find($id);
        return view($this->viewPath.'request', compact('request'));
    }

    public function updateRequest(Request $request)
    {
        $req = Flight::findOrFail($request->get('request'));
        $inputs = $request->only(['status', 'admin_comment']);
        if($req->update($inputs))
            return back()->with('msg', trans('common.update-success'));

        return back()->with('msg', trans('common.update-failed'));
    }
}

resources/views/backend/visas/form.blade.php
@extends('backend.common.template')

@section('title'){{ $title }}@stop

@section('content')
    {{ (isset($visaData)) ? Form::model($visaData, array('url' => LaraLocale::getLocalizedURL(LaraLocale::getCurrentLocale(), route('visa.update', [$visaData->id])), 'method' => 'PUT')) : Form::open(['url' => LaraLocale::getLocalizedURL(LaraLocale::getCurrentLocale(), route('visa.store'))]) }}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            @if(Session::has('msg')){!! Session::get('msg') !!}@endif
            @if(!empty($errors->all()))
                <ul class="callout callout-danger">
                    @foreach($errors->all('<li>:message</li>') as $message) {!! $message !!}  @endforeach
                </ul>
            @endif

            <div class="col-md-8">
                @foreach(LaraLocale::getSupportedLocales() as $localeCode => $properties)
                    <div class='box box-info'>
                        <div class='box-header'>
                            <h3 class='box-title'><small>{!! trans('common.'.$localeCode.'-flag') !!}</small> {{ $properties['native'] }}</h3>
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                                <button type="button" class="btn btn-info btn-sm" data-widget='collapse' data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                            </div><!-- /. tools -->
                        </div><!-- /.box-header -->
                        <div class='box-body pad'>
                            <div class="form-group">
                                {{ Form::label('title_'.$localeCode, trans('visas.title').':') }}
                                {{ Form::text('title_'.$localeCode, old('title_'.$localeCode), array('class' => 'form-control', 'placeholder' => trans('visas.title'), 'required')) }}
                            </div>
                            <div class="form-group">
                                {{ Form::label('description_'.$localeCode, trans('visas.description').':') }}
                                {{ Form::textarea('description_'.$localeCode, old('description_'.$localeCode), array('class' => 'form-control', 'placeholder' => trans('visas.description'))) }}
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            <div class="col-md-4">
                <div class="box box-success">
                    <div class='box-header'>
                        <!-- tools box -->
                        <div class="pull-right box-tools">
                            <button type="button" class="btn btn-info btn-sm" data-widget='collapse' data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                        </div><!-- /. tools -->
                    </div><!-- /.box-header -->
                    <div class='box-body pad'>
                        <div class="form-group">
                            {{ Form::label('country_id', trans('countries.title').':') }}
                            {{ Form::select('country_id', $countries, old('country_id'), ['id' => 'country_id', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('price', trans('visas.price').':') }}
                            {{ Form::text('price', old('price'), ['class' => 'form-control', 'placeholder' => trans('visas.price'), 'required']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('has_shipping', trans('visas.has-shipping').':') }}
                            {{ Form::select('has_shipping', array('0' => trans('common.no'),'1' => trans('common.yes')), old('has_shipping'), ['id' => 'has_shipping', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group hasShipping" style="{{ (isset($visaData) && $visaData->has_shipping) ? 'display:block' : 'display: none' }}">
                            {{ Form::label('middle_price', trans('visas.middle-price').':') }}
                            {{ Form::text('middle_price', old('middle_price'), ['class' => 'form-control', 'placeholder' => trans('visas.middle-price')]) }}
                        </div>
                        <div class="form-group hasShipping" style="{{ (isset($visaData) && $visaData->has_shipping) ? 'display:block' : 'display: none' }}">
                            {{ Form::label('east_west_price', trans('visas.east-west-price').':') }}
                            {{ Form::text('east_west_price', old('east_west_price'), ['class' => 'form-control', 'placeholder' => trans('visas.east-west-price')]) }}
                        </div>
                        <div class="form-group hasShipping" style="{{ (isset($visaData) && $visaData->has_shipping) ? 'display:block' : 'display: none' }}">
                            {{ Form::label('south_price', trans('visas.south-price').':') }}
                            {{ Form::text('south_price', old('south_price'), ['class' => 'form-control', 'placeholder' => trans('visas.south-price')]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('status', trans('common.status').':') }}
                            {{ Form::select('status', array('1' => trans('common.active'),'0' => trans('common.deactive')), old('status'), ['id' => 'status', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('featured', trans('common.featured').':') }}
                            {{ Form::select('featured', array('0' => trans('common.no'),'1' => trans('common.yes')), old('featured'), ['id' => 'featured', 'class' => 'form-control']) }}
                        </div>
                    </div>
                </div>

                {{ Form::submit(trans('common.save'), array('class' => 'btn btn-primary')) }}
            </div>
        </div>
    </div>
    {{ Form::close() }}
@stop

@section('scripts')
    <script src="//cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>
    @foreach(LaraLocale::getSupportedLocales() as $localeCode => $properties)
        <script type="text/javascript">
            $(function() { CKEDITOR.replace('description_{{$localeCode}}', {language: "{{$localeCode}}"}); });
        </script>
    @endforeach
    <script type="application/javascript">
        $(document).ready(function () {
            $('#has_shipping').on('change', function () {
                if($(this).val() > 0){
                    $('.hasShipping').fadeIn();
                }else{
                    $('.hasShipping').fadeOut();
                }
            });
        });
    </script>
@stop

resources/views/backend/visas/list.blade.php
@extends('backend.common.template')

@section('title'){{ trans('visas.visas')}} @stop

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    @if(Session::has('msg')){!! Session::get('msg') !!}@endif
                </div><!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table id="example1" class="table table-bordered table-striped text-center">
                        <thead>
                        <tr>
                            <th>{{ trans('visas.title') }}</th>
                            <th>{{ trans('countries.title') }}</th>
                            <th>{{ trans('common.status') }}</th>
                            <th>{{ trans('common.featured') }}</th>
                            <th>{{ trans('visas.documents') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($allVisas as $visa)
                            <tr>
                                <td>{{ $visa->title_ar }}<br/>{{ $visa->title_fr }}</td>
                                <td>{{ $visa->country->name_ar }}<br/>{{ $visa->country->name_fr }}</td>
                                <td><img src="{{ asset('assets/backend/img/status_'.$visa->status.'.png') }}" /></td>
                                <td><img src="{{ asset('assets/backend/img/status_'.$visa->featured.'.png') }}" /></td>
                                <td><a href="{{ route('documents.index', [$visa->id]) }}"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></td>
                                <td><a href="{{ route('visa.edit', [$visa->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a></td>
                                <td>
                                    {{ Form::open(['url' => route('visa.destroy', [$visa->id]), 'method' => 'DELETE']) }}
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="confirm('{{trans('common.delete-confirm')}}');"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>{{ trans('visas.title') }}</th>
                            <th>{{ trans('countries.title') }}</th>
                            <th>{{ trans('common.status') }}</th>
                            <th>{{ trans('common.featured') }}</th>
                            <th>{{ trans('visas.documents') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>

@stop

@section('scripts')
    {{ Html::style('assets/backend/css/datatables/dataTables.bootstrap.css') }}
    {{ Html::script('assets/backend/js/plugins/datatables/jquery.dataTables.js') }}
    {{ Html::script('assets/backend/js/plugins/datatables/dataTables.bootstrap.js') }}
    <script type="text/javascript">
        $(function() {
            $("#example1").dataTable();
        });
    </script>
@stop