routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('upload/temp', 'Controller@uploadTemp')->name('upload.temp');

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group([ 'prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ] ], function (){
    Route::group(['prefix' => 'backend', 'namespace' => 'backend'], function($route) {
        Route::group(['namespace' => 'Auth'], function () {
            //Admin Login
            Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
            Route::post('login', 'LoginController@login')->name('admin.login');
            Route::get('logout', 'LoginController@logout')->name('admin.logout');
            //Admin Passwords
            Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.send.reset');
            Route::post('password/reset', 'ResetPasswordController@reset')->name('admin.reset');
            Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.reset');
            Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.reset.form');
        });

        Route::group(['middleware' => 'admin'], function () {
            Route::resource('navigations', 'NavigationsController')->except('show');
            Route::resource('slides', 'SlidesController')->except('show');
            Route::resource('countries', 'CountriesController')->except('show');
            Route::resource('cities', 'CitiesController')->except('show');
            Route::get('cities/country/{coid}/{ctid?}', 'CitiesController@country')->name('cities.country');
            Route::resource('pages', 'PagesController')->except('show');
            Route::resource('admins', 'AdminsController')->except('show');
            Route::resource('users', 'UsersController')->except('show');
            Route::get('users/generate', 'UsersController@generate')->name('users.generate');
            Route::resource('visa', 'VisasController')->except('show');
            Route::get('visa/requests', 'VisasController@requests')->name('visa.requests');
            Route::get('visa/request/{id}', 'VisasController@showRequest')->name('visa.request');
            Route::post('visa/request/edit', 'VisasController@updateRequest')->name('visa.request.edit');
            Route::get('documents/{visa}', 'DocumentsController@index')->name('documents.index');
            Route::get('documents/create/{visa}', 'DocumentsController@create')->name('documents.create');
            Route::resource('documents', 'DocumentsController')->except('index','create','show');

            Route::resource('hotels', 'HotelsController')->except('show');
            Route::match(['get','post'], 'hotels/album/{hotel}', 'HotelsController@album')->name('hotels.album');
            Route::get('hotels/album/makeFeatured/{photo}', 'HotelsController@makeFeatured')->name('hotels.album.featured');
            Route::delete('hotels/photo/{photo}', 'HotelsController@destroyPhoto')->name('hotels.photo.destroy');
            Route::get('hotels/requests', 'HotelsController@requests')->name('hotels.requests');
            Route::get('hotels/request/{id}', 'HotelsController@showRequest')->name('hotels.request');
            Route::post('hotels/request/edit', 'HotelsController@updateRequest')->name('hotels.request.edit');
            Route::get('hotels/custom/requests', 'HotelsController@requestsCustom')->name('hotels.requests-custom');
            Route::get('hotels/request/custom/{id}', 'HotelsController@showRequestCustom')->name('hotels.request.custom');
            Route::post('hotels/request/custom/edit', 'HotelsController@updateRequestCustom')->name('hotels.request.custom.edit');

            Route::resource('amenities', 'AmenitiesController')->except('show', 'create', 'edit', 'update');

            Route::post('rooms/removePhoto', 'RoomsController@removeImg')->name('room.photo.delete');
            Route::get('rooms/{hotel}', 'RoomsController@index')->name('rooms.index');
            Route::get('rooms/create/{hotel}', 'RoomsController@create')->name('rooms.create');
            Route::resource('rooms', 'RoomsController')->except('show', 'index', 'create');

            Route::resource('trips', 'TripsController')->except('show');
            Route::get('trips/requests', 'TripsController@requests')->name('trips.requests');
            Route::get('trips/request/{id}', 'TripsController@showRequest')->name('trips.request');
            Route::match(['get','post'], 'trips/album/{trip}', 'TripsController@album')->name('trips.album');
            Route::post('trips/request/edit', 'TripsController@updateRequest')->name('trips.request.edit');
            Route::get('trips/album/makeFeatured/{photo}', 'TripsController@makeFeatured')->name('trips.album.featured');
            Route::delete('trips/photo/{photo}', 'TripsController@destroyPhoto')->name('trips.photo.destroy');

            Route::get('flights/requests', 'FlightsController@requests')->name('flights.requests');
            Route::get('flights/request/{id}', 'FlightsController@showRequest')->name('flights.request');
            Route::post('flights/request/edit', 'FlightsController@updateRequest')->name('flights.request.edit');

            Route::match(['get', 'post'], 'settings', 'SettingsController@index')->name('settings');            // Site Settings
            Route::match(['get', 'post'], 'terms', 'SettingsController@terms')->name('terms');                  // Terms Settings
            Route::match(['get', 'post'], 'contacts', 'SettingsController@contacts')->name('contacts');         // Contacts Info Settings
            Route::get('contact-us', 'DashboardController@contact')->name('contact-us');                                    // Contact Us Emails
            Route::get('newsletter', 'NewsletterController@index')->name('newsletter');                                    // Backend Dashboard
            Route::post('newsletter', 'NewsletterController@send')->name('newsletter');                                    // Backend Dashboard
            Route::get('/', 'DashboardController@index')->name('dashboard');                                    // Backend Dashboard
        });
    });

    Route::group(['namespace' => 'frontend'], function($route) {
        Route::group(['middleware' => 'user'], function (){
            Route::get('profile', 'UsersController@profile')->name('site.profile');
            Route::put('profile', 'UsersController@profileHandle')->name('site.profile');

            Route::get('agency/trips', 'UsersController@trips')->name('agency.trips');
            Route::match(['get', 'post'], 'agency/trips/create', 'UsersController@createTrip')->name('agency.trips.create');
            Route::match(['get', 'put'], 'agency/trips/edit/{id}', 'UsersController@editTrip')->name('agency.trips.edit');
            Route::delete('agency/trips/destroy/{id}', 'UsersController@destroyTrip')->name('agency.trips.destroy');
            Route::match(['get', 'post'], 'agency/trips/album/{trip}', 'UsersController@tripAlbum')->name('agency.trips.album');
            Route::get('agency/trips/album/makeFeatured/{photo}', 'UsersController@makeFeatured')->name('agency.trips.album.featured');
            Route::delete('agency/trips/photo/{photo}', 'UsersController@destroyPhoto')->name('agency.trips.photo.destroy');

            Route::post('visa-request', 'VisasController@visaRequest')->name('site.visa.request');
            Route::get('my-visas', 'VisasController@myVisasRequests')->name('site.my-visas');

            Route::post('hotels/special', 'HotelsController@custom')->name('site.hotels.custom');
            Route::post('hotels/bookingConfirm', 'HotelsController@bookingConfirm')->name('site.hotels.booking.confirm');
            Route::post('hotels/{id}', 'HotelsController@booking')->name('site.hotels.booking');
            Route::get('my-hotels', 'HotelsController@myHotelsRequests')->name('site.my-hotels');
            Route::get('my-hotels/special', 'HotelsController@myHotelsRequestsCustom')->name('site.my-hotels.custom');

            Route::post('trips/{id}', 'TripsController@bookingConfirm')->name('site.trips.booking');
            Route::get('my-trips', 'TripsController@myTripsRequests')->name('site.my-trips');
            Route::get('my-trips-requests', 'TripsController@agencyTripsRequests')->name('site.agency-trips-requests');

            Route::post('flights/booking', 'FlightsController@booking')->name('site.flight.booking');
            Route::get('my-flights', 'FlightsController@myFlightsRequests')->name('site.my-flights');
            Route::get('flight/{id}', 'FlightsController@show')->name('site.flight.show');

            Route::get('payments/upload/{action}/{id}', 'PaymentsController@paymentUpload')->name('site.payments.upload');
            Route::post('payments/upload', 'PaymentsController@paymentUploadHandle')->name('site.payments.upload.post');
        });

        Auth::routes();
        Route::get('register/agency', 'Auth\RegisterController@showAgencyRegistrationForm')->name('register.agency');

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{

    protected $fillable = [
        'slug', 'title_ar', 'title_fr', 'image', 'content_ar', 'content_fr', 'status', 'created_by', 'updated_by'
    ];

    public static $rules = [
        'title_ar' => 'required', 'title_fr' => 'required', 'content_ar' => 'required', 'content_fr' => 'required'
    ];

    protected function getTitleAttribute()
    {
        return $this->{"title_".\LaraLocale::getCurrentLocale()};
    }

    protected function getContentAttribute()
    {
        return $this->{"content_".\LaraLocale::getCurrentLocale()};
    }

    protected static function boot()
    {
        parent::boot();

        static::deleted(function ($model)
        {
            if(!empty($model->image)){
                \File::delete(storage_path('upload/pages/'.$model->image));
                \File::delete(storage_path('upload/pages/thumbnail-'.$model->image));
                \File::delete(storage_path('upload/pages/small-'.$model->image));
                \File::delete(storage_path('upload/pages/medium-'.$model->image));
                \File::delete(storage_path('upload/pages/large-'.$model->image));
            }
        });
    }
}

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    public $guarded = ['id'];

    public static function rules(){
        foreach(\LaraLocale::getSupportedLocales() as $localeCode => $properties){
            $rules['site_name_'.$localeCode] = 'required';
        }
        $rules['currency_rate'] = 'required';

        return $rules;
    }

    public static $messages = [
        'site_name_ar.required' => 'اسم الموقع العربي مطلوب!',
        'site_name_en.required' => 'اسم الموقع الإنجليزي مطلوب!',
        //'site_email.required'   => 'بريد الموقع الإلكتروني مطلوب!',
        //'site_email.email'      => 'البريد الإلكتروني غير صحيح!'
    ];

    public function getSiteNameAttribute()
    {
        return $this->{"site_name_".\LaraLocale::getCurrentLocale()};
    }

    public function getSiteMetakeyAttribute()
    {
        return $this->{"site_metakey_".\LaraLocale::getCurrentLocale()};
    }

    public function getSiteMetadescAttribute()
    {
        return $this->{"site_metadesc_".\LaraLocale::getCurrentLocale()};
    }

    public function getSiteAddressAttribute()
    {
        return $this->{"address_".\LaraLocale::getCurrentLocale()};
    }

    public function getContactPageAttribute()
    {
        return $this->{"contact_page_".\LaraLocale::getCurrentLocale()};
    }

    public function getVisasTermsAttribute()
    {
        return $this->{"visas_terms_".\LaraLocale::getCurrentLocale()};
    }

    public function getHotelsTermsAttribute()
    {
        return $this->{"hotels_terms_".\LaraLocale::getCurrentLocale()};
    }

    public function getTripsTermsAttribute()
    {
        return $this->{"trips_terms_".\LaraLocale::getCurrentLocale()};
    }

    public function getFlightsTermsAttribute()
    {
        return $this->{"flights_terms_".\LaraLocale::getCurrentLocale()};
    }

    public function getAgenciesTermsAttribute()
    {
        return $this->{"agencies_terms_".\LaraLocale::getCurrentLocale()};
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Notifications\CustomResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public static function createRules()
    {
        $rules = [
            'firstname' => 'required|string|max:255',
            'lastname'  => 'required|string|max:255',
            'section'   => 'required|string|max:255',
            'town'      => 'required|string|max:255',
            'state'     => 'required|string|max:255',
            'address'   => 'required|string|max:255',
            'email'     => 'required|string|email|max:255|unique:users',
            'password'  => 'required|string|min:6|confirmed',
        ];

        if(\Request::get('type') == 'agency'){
            $rules['license_number'] = 'required';
            $rules['image'] = 'image';
        }

        return $rules;
    }

    public static function updateRules()
    {
        $rules = [
            'firstname' => 'required|string|max:255',
            'lastname'  => 'required|string|max:255',
            'section'   => 'required|string|max:255',
            'town'      => 'required|string|max:255',
            'state'     => 'required|string|max:255',
            'address'   => 'required|string|max:255',
        ];

        if(\Request::get('type') == 'agency'){
            $rules['license_number'] = 'required';
        }

        if(\Request::has('password') && !empty(\Request::get('password'))){
            $rules['password']  = 'required|string|min:6|confirmed';
        }

        return $rules;
    }

    public static function rulesMsgs()
    {
        return [
            'required' => trans('validation.required', ['attribute' => '']),
        ];
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CustomResetPassword($token));
    }

    public function agencyTrips()
    {
        return $this->hasMany(Trip::class, 'created_by');
    }
}

resources/views/frontend/common/partials/_documents.blade.php
@if(count($documents))
    @for($x=0;$x<$count;$x++)
        <h5>{{ trans('visas.person-docs.'.$x) }}</h5>
        <div class="divider margin5 hr5"><span></span></div>
        @foreach($documents as $doc)
            <div class="col-md-2 col-sm-4">
                <div id="file_{{$x}}_{{$doc->id}}" class="dropzone"></div>
                <p>{{ $doc->title }}</p>
                @if($doc->has_app)
                    <a href="{{ route('image', ['visas', $doc->application]) }}" target="_blank" download class="btn btn-success downloadApp"><i class="fa fa-download"></i></a>
                @endif
            </div>
        @endforeach
        <div class="clearfix"></div>
    @endfor
@endif

resources/views/frontend/common/partials/_footer.blade.php
<!-- footer widget ==================================== -->
<section class="footer-widget">
    <div class="container">
        <div class="row with-border">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="footer-item contact-info">
                    <h4>{{ trans('contact.contact-info') }}</h4>
                    <ul>
                        <li><i class="fa fa-building-o"></i><span>{{ $config->site_name }}</span></li>
                        <li><i class="fa fa-map-marker"></i><span>{{ $config->site_address }}</span></li>
                        <li><i class="fa fa-phone"></i><span>{{ $config->site_phone }}</span></li>
                        <li><i class="fa fa-envelope-o"></i><span><a href="mailto:{{ $config->site_email }}">{{ $config->site_email }}</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="footer-item recent-posts">
                    <ul>
                        <li><a href="{{ route('site.visas.index') }}">{{ trans('visas.visas') }}</a></li>
                        <li><a href="{{ route('site.hotels.index') }}">{{ trans('hotels.hotels') }}</a></li>
                        <li><a href="{{ route('site.trips.index') }}">{{ trans('trips.trips') }}</a></li>
                        <li><a href="{{ route('site.flights') }}">{{ trans('flights.flights') }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 hidden-sm hidden-xs">
                <div class="footer-item recent-posts">
                    <h4>{{ trans('common.find-facebook') }}</h4>
                    <div class="fb-page" data-href="https://www.facebook.com/Voyagedz1" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Voyagedz1" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Voyagedz1">voyagedz.com</a></blockquote></div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End footer widget ==================================== -->

<!-- footer ==================================== -->
<footer class="footer">
    <div class="container">
        <p class="copyright pull-left item_left"><strong>{{ trans('common.copyrights', ['siteName' => $config->site_name]) }}</strong></p>
        <ul class="pull-right social-links text-center item_right">
            @if($config->twitter)<li><a href="{{$config->twitter}}" target="_blank"><i class="fa fa-twitter"></i></a></li>@endif
            @if($config->instagram)<li><a href="{{$config->instagram}}" target="_blank"><i class="fa fa-instagram"></i></a></li>@endif
            @if($config->facebook)<li><a href="{{$config->facebook}}" target="_blank"><i class="fa fa-facebook"></i></a></li>@endif
            @if($config->youtube)<li><a href="{{$config->youtube}}" target="_blank"><i class="fa fa-youtube"></i></a></li>@endif
        </ul>
    </div>
</footer>
<!-- End footer ==================================== -->

<div class="amg-floating-contacts">
    <div class="amg-floating-contact-wrap amg-green">
        <div class="amg-floating-icon">
            <i class="fa fa-phone"></i>
        </div>
        <div class="amg-floating-link amg-floating-phone">
            <a class="amg-nav-item" href="#">{{ $config->site_phone }}</a>
        </div>
    </div>
</div>

resources/views/frontend/common/partials/_head.blade.php
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <!-- Meta Description -->
    <meta name="description" content="{{ $config->site_metadesc }}">
    <!-- Meta Keyword -->
    <meta name="keywords" content="{{ $config->site_metakey }}">
    <!-- meta character set -->
    <meta charset="utf-8">

    <!-- Site Title -->
    <title>{{ $config->site_name }} :: @yield('title')</title>

    <link rel="shortcut icon" href="{{ asset('assets/frontend/img/favicon.png') }}">

    <!-- CSS ============================================= -->
    <link type="text/css" rel="stylesheet" href="{{ asset('assets/frontend/css/font-awesome.min.css') }}" />
    <link type="text/css" rel="stylesheet" href="{{ asset('assets/frontend/css/bootstrap.min.css') }}" />
    {!! Minify::stylesheet([
//        '/assets/frontend/css/bootstrap.min.css',
        '/assets/frontend/css/jquery.bxslider.css',
        '/assets/frontend/css/animate.css',
        '/assets/frontend/shortcodes/css/main.css',
        '/assets/frontend/shortcodes/css/media-queries.css',
        '/assets/frontend/css/main.css',
        '/assets/frontend/css/media-queries.css',
    ]) !!}

    @if(LaraLocale::getCurrentLocale() == 'ar')
        {!! Minify::stylesheet([
            '/assets/backend/css/bootstrap-rtl.min.css',
            '/assets/frontend/css/main-rtl.css'
        ]) !!}
    @endif
    <link id="themeColorChangeLink" type="text/css" rel="stylesheet" href="{{ asset('assets/frontend/css/colors/c10.css') }}">

    @yield('styles')

    <!--[if lt IE 9]>
    {!! Minify::javascript([
        '//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js',
        '//oss.maxcdn.com/respond/1.4.2/respond.min.js'
    ]) !!}
    <![endif]-->
</head>

resources/views/frontend/common/partials/_header.blade.php
<header id="head" class="navbar-default sticky-header">
    <div class="container">
        @include('frontend.common.partials._nav')
    </div>
</header>

resources/views/frontend/common/partials/_nav.blade.php
<div class="mega-menu-wrapper border clear">
    <div class="navbar-header">
        <!-- responsive nav button -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- /responsive nav button -->
        <!-- logo -->
        <a class="navbar-brand" href="{{route('site.home')}}">
            <img src="{{ asset('assets/frontend/img/logo.jpg') }}" alt="{{ $config->site_name }}" height="80">
        </a>
        <!-- /logo -->
    </div>
    <!-- main nav -->
    <nav class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            @foreach($mainNav as $item)
                <li @if(LaraLocale::getNonLocalizedURL($item->link) == LaraLocale::getNonLocalizedURL(url()->current())) class="current" @endif>
                    <a href="{{ LaraLocale::getLocalizedURL(LaraLocale::getCurrentLocale(), $item->link) }}">
                        {{ $item->title }}
                    </a>
                    @if(count($item->childrenItems))
                    <ul class="sub-menu">
                        @foreach($item->childrenItems as $subitem)
                            <li>
                                <a href="{{ LaraLocale::getLocalizedURL(LaraLocale::getCurrentLocale(), $subitem->link) }}">
                                    {{ $subitem->title }}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                    @endif
                </li>
            @endforeach
        </ul>
    </nav>
    <!-- /main nav -->
</div>

resources/views/frontend/common/partials/_search.blade.php
<div class="search-tabs">
    <div class="container">
        <div class="search-tab-content">
            <!-- Nav tabs -->
            <ul class="search-tab-nav">
                <li class="toggle-form">
                    <a href="javascript:;"><h2><i class="fa fa-angle-up"></i>{{ trans('hotels.search-for-hotel') }}</h2></a>
                </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active" id="hotels">
                    <div class="tab-search-form">
                        <form action="{{route('site.hotels.index')}}" class="ts-form1">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <label for="Country">{{ trans('countries.country') }}</label>
                                        <select name="country" id="Country" class="form-control">
                                            <option value="0" selected>{{ trans('countries.select') }}</option>
                                            @foreach($countries as $country)
                                                <option value="{{$country->slug}}">{{ $country->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <label for="City">{{ trans('cities.city') }}</label>
                                        <select name="city" id="City" class="form-control">
                                            <option value="0" selected>{{ trans('cities.select') }}</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <i class="fa fa-calendar input-icon"></i>
                                        <label for="checkin">{{ trans('hotels.checkin') }}</label>
                                        <input type="text" class="form-control datepicker" name="checkin" id="checkin" placeholder="{{ trans('hotels.checkin') }}">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <i class="fa fa-calendar input-icon"></i>
                                        <label for="checkout">{{ trans('hotels.checkout') }}</label>
                                        <input type="text" class="form-control datepicker2" name="checkout" id="checkout" placeholder="{{ trans('hotels.checkout') }}">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <i class="fa fa-home input-icon"></i>
                                        <label for="adults">{{ trans('hotels.adults') }}</label>
                                        <input type="number" class="form-control" name="adults" id="adults" placeholder="{{ trans('hotels.adults') }}">
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="input-field">
                                        <i class="fa fa-user input-icon"></i>
                                        <label for="Childes">{{ trans('hotels.childes') }}</label>
                                        <input type="number" class="form-control" name="childes" id="Childes" placeholder="{{ trans('hotels.childes') }}">
                                    </div>
                                </div>
                            </div>
                            <input type="submit" value="{{ trans('common.search') }}" class="btn btn-blue">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('styles')
    {!! Minify::stylesheet('/assets/frontend/css/jquery-ui.min.css') !!}
@append

@section('scripts')
    {!! Minify::javascript('/assets/frontend/js/jquery-ui.min.js') !!}
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                minDate: 0,
                dateFormat: 'yy-mm-dd',
                onSelect: function (selected) {
                    $('#checkout').datepicker('option', 'minDate', selected)
                }
            });

            $(".datepicker2").datepicker({
                minDate: 0,
                dateFormat: 'yy-mm-dd',
                onSelect: function (selected) {
                    $('#checkin').datepicker('option', 'maxDate', selected)
                }
            });

            $("form.ts-form1").submit(function() {
                $(this).find(':input').filter(function() { return !this.value; }).attr('disabled', 'disabled');
                return true;
            });

            $('#Country').on('change', function () {
                getCountryCities($(this).val());
            });

            function getCountryCities(co) {
                $.ajax({
                    url: '/getCountryCities/'+co,
                    method: 'GET',
                    success: function (response) {
                        if(response.citiesList != ''){
                            $('#City').html(response.citiesList);
                        }
                    }
                });
            }
        });
    </script>
@append

resources/views/frontend/common/partials/_welcomebar.blade.php
@if(auth()->guard('user')->check() && auth()->guard('user')->user()->type == 'agency')
<div id="welcome-bar" style="background-color: {{ auth()->guard('user')->user()->background_color ?? '#339933' }}">
	<div class="container">
		<div class="col-md-6">
			<h3 style="color: {{ auth()->guard('user')->user()->font_color ?? '#ffffff' }}">{{ trans('users.welcome'). ' ' . auth()->guard('user')->user()->fullname }}</h3>
		</div>
		<div class="col-md-6 text-right">
			@if(auth()->guard('user')->user()->photo)
				<img src="{{ route('image', ['users', auth()->guard('user')->user()->photo]) }}" alt="{{ auth()->guard('user')->user()->fullname }}">
			@endif
		</div>
	</div>
</div>
<div class="clearfix"></div>
@endif